FROM elasticsearch
MAINTAINER Peter Klipfel <peter@archethought.com>

ADD config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

CMD ["/usr/share/elasticsearch/bin/elasticsearch"]

